manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: protocentral
      url-base: https://github.com/Protocentral

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.2
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - cmsis-dsp
          - fatfs
          - hal_nordic
          - libmetal
          - littlefs
          - lvgl
          - mbedtls
          - mcuboot
          - open-amp
          - picolibc
          - segger
          - tf-psa-crypto
          - zcbor
      clone-depth: 1

#    - name: max30001
#      repo-path: protocentral_max30001_zephyr_driver
#      remote: protocentral
#      revision: main
#      path: drivers/sensor/max30001
