// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include <zephyr/kernel.h>
#include <zephyr/drivers/spi.h>
#include <zephyr/logging/log.h>
#include <zephyr/device.h>
#include <zephyr/drivers/display.h>
#include <lvgl.h>
#include <stdio.h>
#include <zephyr/smf.h>
#include <app_version.h>
#include <zephyr/logging/log.h>

#include <time.h>
#include <zephyr/posix/time.h>
#include <zephyr/drivers/rtc.h>

#include "hw_module.h"
#include "sampling_module.h"
#include "ui/move_ui.h"

/*void ui_event_comp_dailymissiongroup_daily_mission_arc(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t **comp_dailymissiongroup = lv_event_get_user_data(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(comp_dailymissiongroup[UI_COMP_DAILYMISSIONGROUP_MISSION_PERCENT], target, "", "%");
    }
}*/

// COMPONENT dailymissiongroup

lv_obj_t *cui_daily_mission_arc;
lv_obj_t *cui_daily_mission_arc_2;

lv_obj_t *ui_dailymissiongroup_create(lv_obj_t *comp_parent)
{
    lv_obj_t *cui_dailymissiongroup;
    cui_dailymissiongroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_dailymissiongroup, 390);
    lv_obj_set_height(cui_dailymissiongroup, 390);
    lv_obj_set_align(cui_dailymissiongroup, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(cui_dailymissiongroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(cui_dailymissiongroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dailymissiongroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Green arc
    cui_daily_mission_arc = lv_arc_create(cui_dailymissiongroup);

    lv_obj_set_size(cui_daily_mission_arc, 360, 360);
    lv_obj_set_align(cui_daily_mission_arc, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_daily_mission_arc, LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_arc_set_value(cui_daily_mission_arc, 25);
    lv_arc_set_bg_angles(cui_daily_mission_arc, 90, 180);
    lv_obj_set_style_arc_color(cui_daily_mission_arc, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_daily_mission_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_daily_mission_arc, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(cui_daily_mission_arc, lv_color_hex(0xB0E14A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_daily_mission_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_daily_mission_arc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(cui_daily_mission_arc, 7, LV_PART_MAIN);      // Changes background arc width
    lv_obj_set_style_arc_width(cui_daily_mission_arc, 7, LV_PART_INDICATOR); // Changes set part width

    lv_obj_set_style_bg_color(cui_daily_mission_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_daily_mission_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Red arc
    cui_daily_mission_arc_2 = lv_arc_create(cui_dailymissiongroup);

    lv_obj_set_size(cui_daily_mission_arc_2, 360, 360);
    lv_obj_set_align(cui_daily_mission_arc_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_daily_mission_arc_2, LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_arc_set_value(cui_daily_mission_arc_2, 75);
    lv_arc_set_bg_angles(cui_daily_mission_arc_2, 270, 0);
    lv_obj_set_style_arc_color(cui_daily_mission_arc_2, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_daily_mission_arc_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_daily_mission_arc_2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(cui_daily_mission_arc_2, lv_color_hex(0xB00000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_daily_mission_arc_2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_daily_mission_arc_2, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(cui_daily_mission_arc_2, 7, LV_PART_MAIN);      // Changes background arc width
    lv_obj_set_style_arc_width(cui_daily_mission_arc_2, 7, LV_PART_INDICATOR); // Changes set part width

    lv_obj_set_style_bg_color(cui_daily_mission_arc_2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_daily_mission_arc_2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    return cui_dailymissiongroup;
}

void ui_dailymissiongroup_update(uint32_t steps_walk, uint32_t steps_run)
{
    if (cui_daily_mission_arc == NULL || cui_daily_mission_arc_2 == NULL)
        return;

    lv_arc_set_value(cui_daily_mission_arc, steps_walk);
    lv_arc_set_value(cui_daily_mission_arc_2, steps_run);
}
