// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_DAILYMISSIONGROUP_H
#define _UI_COMP_DAILYMISSIONGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dailymissiongroup
#define UI_COMP_DAILYMISSIONGROUP_DAILYMISSIONGROUP 0
#define UI_COMP_DAILYMISSIONGROUP_MISSION_PERCENT 1
#define UI_COMP_DAILYMISSIONGROUP_DAILY_MISSION_IMAGE 2
#define UI_COMP_DAILYMISSIONGROUP_DAILY_MISSION_ARC 3
#define _UI_COMP_DAILYMISSIONGROUP_NUM 4
lv_obj_t *ui_dailymissiongroup_create(lv_obj_t *comp_parent);
void ui_event_comp_dailymissiongroup_daily_mission_arc( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
